### ISSUE TITLE
CUDA out of memory when inferencing on single 1920x1440 image

### ISSUE THREAD

**Issue by cy810557** [movingforward100/Shadow_R#1]
Great work! When I run test.py with test images on my 3090 Ti with 24576MiB GPU memory, it returns OOM error. 

So should I resize inputs to 960 x 720 before inferencing, or run with sliding window?

**Comment by movingforward100** [comment]
Thanks for your interest.

Based on my experience, running with sliding window is better. I mean you can try spliting the input into 4 blocks, fedding each block into the network, and combining all outputs into the final result.

**Comment by IgorAherne** [comment]
I've implemented it here https://github.com/IgorAherne/Shadow_R
